// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfbmxcxkxahxzmpjplkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmYm14Y3hreGFoeHptcGpwbGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTkxNTIsImV4cCI6MjA2ODY3NTE1Mn0.sF3od9-VW17CRqRTwSaJWmltGCvPxJNLqWLxeXZYhOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});